#!/usr/bin/perl


use strict;
use lib q[lib]; # for linter


use fairu::config q[meta];
use fairu::chan; # owo
use fairu::chan::default;


# global stuff
my ($file, $mode) = @ARGV;

my $action = lc($mode) eq q[run] || lc($mode) eq q[daemon];
my $run    = lc($mode) eq q[daemon];
my $idle   = 0;
my $reload = 0;
my $watch  = undef;

# setup autoflush
local $| = 1;

# signal handlers
local $SIG{TERM} = sub { $run = 0; fairu::chan::stop() };
local $SIG{USR1} = sub { $idle = 0 };
local $SIG{USR2} = sub { $reload = 1 };

# config some stuff
exit 1 unless (fairu::config::parse($file) == 0);
$idle = (meta->{idleTime} || fairu::chan::default->IDLE) if ($run == 1);

if ($run && meta->{autoreload})
{
  if (eval { require File::Monitor })
  {
    $watch = File::Monitor->new();
    $watch->watch($file, sub { $reload = 1; $idle = 0 });
  }
  else
  {

  }
}

# first run
fairu::chan::uwu($action);

# go daemon if requested
while ($run)
{
  $watch->scan if defined($watch);

  sleep(meta->{waitTime} || fairu::chan::default->WAIT);
  $idle -= meta->{waitTime} || fairu::chan::default->WAIT;

  if ($run && $reload)
  {
    $reload = 0;
    fairu::config::parse($file);
  }

  if ($run && $idle <= 0)
  {
    $idle = meta->{idleTime} || fairu::chan::default->IDLE;

    fairu::chan::uwu($action);
  }
}

# bye felicia~
exit 0;
